language: node_js
node_js:
  - "4"
matrix:
  fast_finish: true
script: "npm run-script test-travis"
notifications:
  webhooks:
      urls:
        - https://www.travisbuddy.com/
      on_success: never
      on_failure: always
      on_start: never
      on_cancel: never
      on_error: never
